#!/bin/bash
usage() {
    echo "Usage: capsmod [-d] [SEARCH_DIR]"
    echo "    -d            Convert to uppercase"
    echo "    SEARCH_DIR    Directory to search, defaults to current directory"
}

to_upper=0
search_dir=""

while [[ $# > 0 ]]; do
    cur=$1; shift

    if [[ $cur == "-d" ]]; then
        to_upper=1
    else
        if [[ -n $search_dir ]]; then
            usage
            exit 1
        else
            search_dir=$cur
        fi
    fi
done

for file in $(find $search_dir); do
    if [[ -d $file ]]; then
        continue;
    fi

    from=$(basename $file | dd conv=ucase status=none)
    to=$(basename $file | dd conv=lcase status=none)
    
    if [[ $to_upper == 1 ]]; then
        tmp=$from
        from=$to
        to=$tmp
    fi

    if [[ $(basename $file) == $from ]]; then
        target=$(dirname $file)/$to
        if [[ -e $target ]]; then
            echo "Error: wanted to rename $file to $target, but target exists" >&2
            exit 1
        fi
        mv $file $target
    fi
done
